version: '3.7'
services:
    nginx:
        image: nginx:latest
        ports:
            - target: 80
              published: 80
              protocol: tcp
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
        depends_on:
            - client       
    client:
        build:
            context: ./client
        ports:
            - target: 8089
              published: 8089
              protocol: tcp      
